import os

# The official BIP39 English wordlist - fetched directly from the BIP39
# spec's own repository (bitcoin/bips) and verified: exactly 2048 entries,
# no duplicates, alphabetically sorted, lowercase. This list is NOT
# arbitrary or "nothing up my sleeve" derived - it's a fixed, standardized
# list every BIP39-compatible wallet must use verbatim, or mnemonics
# generated by one wallet won't be understood by another.
_WORDLIST_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "wordlist_english.txt")

with open(_WORDLIST_PATH, encoding="utf-8") as _f:
    WORDLIST = [line.strip() for line in _f if line.strip()]

assert len(WORDLIST) == 2048
assert len(set(WORDLIST)) == 2048

WORD_TO_INDEX = {word: index for index, word in enumerate(WORDLIST)}
